pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - export IMAGE_NAME=sshify/ttymi-server:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
