pipelines:
  branches:
    production:
      - step:
          services:
            - docker
          script:
            - export IMAGE_NAME=pldin601/etty-web
            - docker build -t $IMAGE_NAME:latest .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$BITBUCKET_COMMIT
            - docker push $IMAGE_NAME:latest
            - docker push $IMAGE_NAME:$BITBUCKET_COMMIT
      - step:
          script:
            - ssh $DEPLOY_HOST -- docker service update --quiet --force --with-registry-auth --image=$IMAGE_NAME:latest $DEPLOY_SERVICE
